name: "onnx_model"
platform: "onnxruntime_onnx"
max_batch_size: 16

input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [20]
  }
]

output [
  {
    name: "output_1"
    data_type: TYPE_FP32
    dims: [10]
  }
]

instance_group [
  {
    kind: KIND_CPU
  }
]
